language: java
jdk:
  - oraclejdk8
deploy:
  provider: script
  script: "./gradlew bintrayUpload"
  on: 
    tags: true
env:
  global:
  - secure: XX24M8KZq/FNfhGTeE5Ths1G6cIBWZAsERzZF54/nvg6HHx4Dk8SObiAVlBpB2ikDrfzRHPOydUH4thkjyr242b5Y2cgGEzdpAVUJ1SSpxDk/nAmdWQNjhpSmFzY8rkxR6eZFsvPEdG/XrfDa8uTIHtVZmsZkt3mhqsw5gfQyYgK4tdlZ7sd2RjdWRfZFJjT10FzDbif/oCM+o5k89S5AIkNgr7Mv9I45FGc04e5cQdTj79KzYS76NgJY5km6YifTw/X5iQ40uAyreWqhpV2XyI2j/x9En1WoDNwwyUnVWN0JlNbtb4uvPbha/Tqtjezfr9QehXpmN7wUEuLK+XX13hbEu0zuuRBkBjrjWkuv5moZ7bm2bbqDsc0nZFe3VHB7zFe4672ZutM6d1xKTpusSXosP0Axr1xwYXoWyMsCDxqmoDHwVciKlZvN8wr/HvxA8h0/r3IQIUrud8fpZzn8TqcrCzib/VyjsMbbh1R/0FeWwojoFLcB1xg5Fkw0NXkNZiEOt9V3AzMEcK+13vFTsD+i+pUI3WVbjIDyZVzilS17BnJB6LmOQ4Nm9lqNvjEKiRxLQjpzYUkDIJjK8DdI/M+ElP8r36nsQ60ka7O1snPn2S3mla9HfYJeuG2mGlD0UkqK6joVgB8EPYhR9EzHQ8NDk7hMWS+CoLyb+OUF8w=
  - secure: C3VuPKxeXYsmNkpNBq9Wa64uXvBzJ+H2gSSMHm+w9ncgZ7kgLQoZnOf+k91VF39QXFotMFAdRlsR3CPI+c8Di08C5WExfQX1WtEGeubZkOLdTwq2UQN91jMSP9KgxQwRE/b9LZJfFlk7bgwtmaSAGHaitKx+h+TKbJAJOdkTYkYiWSjlE6VJUv/VtUpkH3/mtPovWEJHgku7QVi9dhLYua5gjB4u2NP6GhpbMAwIhQg83nR3AL3MqDMZy9L4d8U2WKbXDjfGUbexxPSCkZbsqrPV5CgaWgmaJ3qrWqpiA0aJVLI6V1ITykPeuKiLvLaoaKDD7wUN5nBX81uT0aAwPwqvmBNi1dPz+TlumQbIhi8xGBPzJPHb0l41CkMzlxhWqWokS98qr6wA0lsd4oi7jR2gNtoOniMDZDQF5FBe/VgGrtQ0DpHR1haeWyRwmZE63JZGiPCBE7INv4er6ojWciCXCt2oteix84JCY4vrsN3hxM2QI/CxahmOCM5oGyohop/ONX6Np2mah0Th3tXkGx8RDHgTkSsLhEDQAQhJ1AS6q574SavBRxT7t8MN1zWgh6iXS++kucr3oS4ZZfwsGUxlBMazydmQucAgb0zL3nMmOvzQxCMbt9Hv1JEjGFx+i2v4PCu26yy660oy3Nl2kWCornLHBCyX8h/ACa929pc=
